Complete ovs_port fix for Ubuntu
https://review.openstack.org/291788 fixed the ovs_port provider
for Red Hat platforms, and identified an issue in ovs.rb, where
self.vlan? and self.bonding? where being used. This fix seemed
incomplete, because in some cases we were still seeing errors in
Ubuntu like
"Error: Could not set 'present' on ensure: undefined method `vlan?'
for Vs_port[loop1](provider=ovs):Puppet::Type::Vs_port::ProviderOvs".

This is fixed by checking if the provider has the requested feature,
instead of using self.vlan? and self.bonding?

Change-Id: I5878448a1616e127c3b39c5f1c446fea151ba202